### ISSUE TITLE
Produce Cad of Current design prediction

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#107]
Produce a cade file that includes the device we aiming to produce
Containing:
* Flavia's lighting setup
* A realistic battery size
* And a resulting realistic enclosure size

**Comment by Gunflower123** [comment]
Completed the last two:
 - Battery size
 - Enclosure for battery+electronics

**Comment by Gunflower123** [comment]
There are some design issues I am having with the enclosure, it isn't fully complete
