### ISSUE TITLE
Capture Subsystem CAD

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#120]
- Camera mount to interface with the tripod
- Filter adapter 
- Right right holder

These can be done in 1 or more Parts as long as it can be 3D printed and they works together

Optional improvement:
-Use clear printing material to make our own lenses

**Comment by Gunflower123** [comment]
I can do this

**Comment by Gunflower123** [comment]
Starting my second design for the clamping stuff

**Comment by Gunflower123** [comment]
I will be closing this issue for now
