### ISSUE TITLE
Define Project Demonstration System

### ISSUE THREAD

**Issue by SamRyder** [ArturCr/Talking-to-Plants#133]

**Comment by ArturCr** [comment]
* Lab-ready system to be able to stimulate a plant with a sinoside using a side-lit defuser
Capture the Florence response and apply segmentation to every image captured
calculating the data block and being capable of displaying the output locally on a computer

* Have a link that brings a user to an online database with a set of datacubes that can be downloaded (ideally browser online)

* (Ideally) Transmit the data cube collected live to the server

**Comment by ArturCr** [comment]
24th March will be the last date before easter so the closest to this deadline should be aimed for the delivery of 1 and 2
