### ISSUE TITLE
Find 3D Printing outsourcing (outside Uni)

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#137]
Get a cost and delivery deadline estimate (find the fastest shipping option)

**Comment by Gunflower123** [comment]
Options
-Hobs 3D

**Comment by ArturCr** [comment]
Please look into multiple options and place there price and delivery time (you can use the Filter holder STL to standardise quota requests)

**Comment by Gunflower123** [comment]
Prof Bruce is looking to find a 3D printing source within UoM

**Comment by ArturCr** [comment]
Royce has soon availability to meet with us on 08/03/2023
