### ISSUE TITLE
Call Walz 

### ISSUE THREAD

**Issue by Gunflower123** [ArturCr/Talking-to-Plants#147]
Give walz a call to ask how long we need to hold their device on a plant for - static device.
Just get a number (hours).

**Comment by ArturCr** [comment]
We can call/email them but odds are they might not reply :C

**Comment by Gunflower123** [comment]
Their phone number is in Germany

**Comment by Gunflower123** [comment]
`They are able to leave it out field for extended durations`

**Comment by ArturCr** [comment]
That is possibly in regards to their mechanical structure as stated by Bruce.
What about the lighting conditions? Can the Leaves be Clamped for that long?

**Comment by flaviamihaela** [comment]
Done by muji
