### ISSUE TITLE
Power PCB schematic

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#148]
Presets task:
* #138 
Will use componets from:
* #113

**Comment by ArturCr** [comment]
I want a review from someone more knowledgeable than me when it comes to batteries. I cannot see anything wrong with this but due to the risk of fire brought about by lithium batteries I want a second opinion

**Comment by ArturCr** [comment]
Minimum track width as per [digikey calculator ](https://www.digikey.co.uk/en/resources/conversion-calculators/conversion-calculator-pcb-trace-width)
| Parameter | value | comment |
|---|---|---|
| I | 2 A | Hopefully only battery terminal, possibly also 3V out|
| Amb temp | 25 C ||
| t | 1 oz  | assumption actual value required|
| Len | 200 mm | overestimation (hopefully) |
| TRise | 10 C ||

Result = 0.78 mm min -> **1 mm MIN!**

**Comment by ArturCr** [comment]
![image](https://user-images.githubusercontent.com/35133970/220778260-89725390-3ed4-4e10-a780-efb10e85a046.png)

**Comment by ArturCr** [comment]
If you don't find a matching Footprint with a quick search. Please just quickly make your own with the dimensions below every single hole uses Male/Female breakout pins size [except the Battery Terminal]

TP4056:
![image](https://user-images.githubusercontent.com/35133970/220779310-b2577f63-f6ed-4bb4-8b54-93e6ee2ec594.png)
XL6009:
![image](https://user-images.githubusercontent.com/35133970/220780121-7facf607-155a-4ef2-9faa-2394369ddce5.png)

**Comment by ArturCr** [comment]
@davidmo13 TODO:
* Find out what is PCB manufacturing Thickness for in-house PCBs
* Find/ make PCB footprints   

@ArturCr TODO:
* Source Screw terminal
* Get a second opinion on the double TP4056 design

**Comment by ArturCr** [comment]
[Battery used](https://uk.rs-online.com/web/p/rechargeable-battery-packs/1449409)
![image](https://user-images.githubusercontent.com/35133970/220784575-f9a16167-7884-4cfd-98c1-7ce121b8a14b.png)
(4 cells ... no load balancer?)
[TP4056 datasheet](https://dlnmh9ip6v2uc.cloudfront.net/datasheets/Prototyping/TP4056.pdf)
(2 TP4056  in parallel?)
[battery datasheet](https://docs.rs-online.com/c5ff/A700000008754101.pdf)
(Still under over current protection 4-7A!)

**Comment by davidmo13** [comment]
PCB manufacturing Thickness for in-house PCBs: 1.55mm thickness, 1oz copper
Available dimensions from @Gunflower123 : similar to LED driver board, less than 80x80mm
Power board 2d layout:
![image](https://user-images.githubusercontent.com/114815988/221835711-c082efa4-1e89-4d7d-855d-010ae5f9f03b.png)

**Comment by davidmo13** [comment]
PCB manufactured and collected
