### ISSUE TITLE
Mesh Network

### ISSUE THREAD

**Issue by SamRyder** [ArturCr/Talking-to-Plants#176]
HIGH PRIORITY:
Test Integration with Button (Justin)
Multiple Images (Justin, Sam)

MEDIUM PRIORITY:
Update run values from Cloud (Justin, Sam)

LOW PRIORITY:
Speed UART up (Justin)
CRC (Justin)

**Comment by JSTUN9** [comment]
Maximum speed (115200 baud rate tested achieved)
