### ISSUE TITLE
Order missing components

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#61]
Components thus identified:
* DAC

depending on what we have available
* opamp
* perf board
* male pin header rows
* female pin header rows
* red camera filter?
* SD *10
* Micro-USB cables
* coper cable spools
* switches 
* screw

**Comment by ArturCr** [comment]
My part has been completed and sent to @flaviamihaela

**Comment by flaviamihaela** [comment]
Done

**Comment by ArturCr** [comment]
Thank you
