### ISSUE TITLE
Agenda review of project finances table

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#62]
Produce and maintain a file that contains all the items we have ordered/ we have access to. 
Identical to the one for IS yet with a link for Agenda to reduce agenda clutter

**Comment by flaviamihaela** [comment]
Done- let me know where i can link it (could even be linked today)
https://livemanchesterac-my.sharepoint.com/:x:/r/personal/bruce_grieve_manchester_ac_uk/_layouts/15/Doc.aspx?sourcedoc=%7BE452D85E-F1F6-478B-8A1C-178924B1C48C%7D&file=4th%20Year%20Project-TTP.xlsx&action=default&mobileredirect=true
