### ISSUE TITLE
A3. lighting PCBs

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#71]
Produce 10 small PCBs to interface with the LED Driver circuit (Make sure to add a mechanical attachment point)
[150283DS73103 (LED)](https://www.mouser.co.uk/datasheet/2/445/150283DS73103-1838914.pdf)

Produce a LED Driver PCB
[dac](https://uk.rs-online.com/web/p/digital-to-analogue-converters/7386027)
[opam](https://uk.farnell.com/texas-instruments/lm358p/ic-op-amp-dual-dip8-358/dp/3117074?st=lm358)
[DIP socket](https://uk.farnell.com/multicomp-pro/mc-2227-08-03-f1/socket-ic-dil-0-3-tube-60-8way/dp/1182585?st=dip%20socket)

[Prototype 1 wiki](https://github.com/ArturCr/Talking-to-Plants/wiki/Prototype-%231#3-lighting-pcbs)

**Comment by ArturCr** [comment]
This design is based on the [DAC datasheet](https://www.farnell.com/datasheets/663139.pdf) but interfaced with the rest of the system components. 
![image](https://user-images.githubusercontent.com/35133970/203393463-be3cb354-f626-49bd-96fb-bb30a65b9194.png)
![image](https://user-images.githubusercontent.com/35133970/203393197-1b21ee58-b167-4ba3-9d93-4d6b31426083.png)

**Comment by davidmo13** [comment]
Sent design of LED PCB to fabrication

**Comment by ArturCr** [comment]
i made prototype board LED Driver with DAC

**Comment by ArturCr** [comment]
The latest LED Driver test has at last exceeded the 100mA threshold. The resulting Schematic is shown below. 
![image](https://user-images.githubusercontent.com/35133970/208241772-59767ae3-0427-482f-9e71-e061abe60fd3.png)

I will aim to complete the design of this PCB and then give it to David for review and to send for manufacturing.

**Comment by ArturCr** [comment]
I believe the PCB is ready for fabrication. The Gerber files:
https://livemanchesterac-my.sharepoint.com/:u:/g/personal/bruce_grieve_manchester_ac_uk/EQX2lgbn1-BCpSP5xYA2abIBrdjq2c3KtGfimEOW0NIFcQ?e=XrrjIJ
