### ISSUE TITLE
A2. Simulate LED and possible LED configurations

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#72]
Do light tests to identify optional LED and LED configurations
[wiki](https://github.com/ArturCr/Talking-to-Plants/wiki/Prototype-%231#2-simulate-led-and-possible-led-configurations)

**Comment by ArturCr** [comment]
Call Paul Wright for ray tracing

**Comment by Gunflower123** [comment]
+ muji on this

**Comment by flaviamihaela** [comment]
This is done
