### ISSUE TITLE
A1. 3D print camera mount

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#75]
[wiki](https://github.com/ArturCr/Talking-to-Plants/wiki/Prototype-%231#1-3d-print-camera-mount-with-the-aim-free)

**Comment by SamRyder** [comment]
First version:
![image](https://user-images.githubusercontent.com/46651067/205050281-855ce327-38c4-4e52-84a7-0a98578e3b44.png)

**Comment by SamRyder** [comment]
Needs screw and threading for parts to be connected
