### ISSUE TITLE
C1. Node transfer speed test

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#80]
[wiki](https://github.com/ArturCr/Talking-to-Plants/wiki/Prototype-%231#1-node-transfer-speed-test)

**Comment by JSTUN9** [comment]
Tested using messages from 1kb to 5kb => roughly 10kb/s transmission rate

**Comment by ArturCr** [comment]
What was your setup? Code? 

Your results should be in table with multiple tests for multiple speeds so that we can  use the scientific method to compare them. Ideally you would also test with different distances 1-40m (but it is a matter of the place where you are testing).
[you can ask the lab space if they have a measuring tape].

**Comment by ArturCr** [comment]
missing documentation
