### ISSUE TITLE
C3. Get a list of all nodes in a mesh 

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#81]
[wiki](https://github.com/ArturCr/Talking-to-Plants/wiki/Prototype-%231#3-get-a-list-of-all-nodes-in-a-mesh-free-once-task-2-is-completed)

**Comment by JSTUN9** [comment]
getNodeList()
function from painless mesh documentation

**Comment by ArturCr** [comment]
Do you have an example of how the function works? Does it detect the depth each node is from the gateway node? Does it always use the same name to allow us to know if a particular node is gone? How did you carry out this tests?
