### ISSUE TITLE
D1. With Spresense Arduino/SDK

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#82]
[wiki](https://github.com/ArturCr/Talking-to-Plants/wiki/Prototype-%231#1-with-spresense-arduino-get)

**Comment by ArturCr** [comment]
current time to GPS accurate time missing

(extra feature) image file access - get jpeg in an SD card then manipulate it

**Comment by SamRyder** [comment]
Original scope complete, extra feature still to be looked at

**Comment by ArturCr** [comment]
Amazing! Thank you
