### ISSUE TITLE
C2. Node Chain message

### ISSUE THREAD

**Issue by ArturCr** [ArturCr/Talking-to-Plants#84]
[wiki](https://github.com/ArturCr/Talking-to-Plants/wiki/Prototype-%231#c2-node-chain-message)

**Comment by JSTUN9** [comment]
painless_mesh API does it already => sendBroadcast() function does it by itself, we can also specify to send to individual nodes

**Comment by ArturCr** [comment]
"(Not broadcast)" is literally on the Wiki for this task! Broadcast does not address the underlying problem trying to be solved here

**Comment by JSTUN9** [comment]
For specific nodes, we can get nodeID using [getNodeList] => then send to specific nodes we want using sendSingle

**Comment by JSTUN9** [comment]
And for identification of our (Gateway node ESP) => we can change what is done within our initialisation function => so all our nodes within our mesh can identify themselves

**Comment by ArturCr** [comment]
missing experiment
